# Generated by Django 4.2.6 on 2023-10-11 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("death_warehouse_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recherchepatient",
            name="code_deces",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="recherchepatient",
            name="date_deces",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recherchepatient",
            name="code_naiss",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="recherchepatient",
            name="lieu_naiss",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="recherchepatient",
            name="pays_naiss",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
