# Generated by Django 4.2.6 on 2023-10-11 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('death_warehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recherchepatient',
            name='code_deces',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recherchepatient',
            name='date_deces',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
