# Generated by Django 4.2.6 on 2023-10-11 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("death_warehouse_app", "0002_recherchepatient_code_deces_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recherchepatient",
            name="code_deces",
        ),
    ]
