# Generated by Django 4.2.6 on 2023-10-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('death_warehouse_app', '0002_recherchepatient_code_deces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherchepatient',
            name='date_deces',
            field=models.DateField(),
        ),
    ]
