# Generated by Django 4.2.6 on 2023-10-13 12:01

import death_warehouse_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('death_warehouse_app', '0003_remove_recherchepatient_code_deces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherchepatient',
            name='date_deces',
            field=death_warehouse_app.models.CustomDateField(blank=True),
        ),
        migrations.AlterField(
            model_name='recherchepatient',
            name='date_naiss',
            field=death_warehouse_app.models.CustomDateField(),
        ),
    ]
