# Generated by Django 4.2.6 on 2023-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('death_warehouse_app', '0003_alter_recherchepatient_date_deces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherchepatient',
            name='date_deces',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='recherchepatient',
            name='date_naiss',
            field=models.DateField(null=True),
        ),
    ]
