# Generated by Django 4.2.6 on 2023-10-13 14:16

import death_warehouse_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('death_warehouse_app', '0004_alter_recherchepatient_date_deces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherchepatient',
            name='date_deces',
            field=death_warehouse_app.models.CustomDateField(blank=True, null=True),
        ),
    ]
