# Generated by Django 4.2.6 on 2023-10-13 14:18

from django.db import migrations

import death_warehouse_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("death_warehouse_app", "0005_alter_recherchepatient_date_deces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recherchepatient",
            name="date_deces",
            field=death_warehouse_app.models.CustomDateField(blank=True, default="1970-01-01", null=True),
        ),
    ]
