# Generated by Django 4.2.6 on 2025-04-16 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("death_warehouse_app", "0007_inseepatient_warehousepatient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("search", "Patient Search"),
                            ("export_csv", "Export to CSV"),
                            ("export_xlsx", "Export to Excel"),
                            ("import_file", "Import File"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
